# edwards25519 parameters
a = -1
d = 37095705934669439343138083508754565189542113879843219016388785533085940283555 
p = 2**255 - 19 # prime, order of Gallois field GF(p)
Gx = 15112221349535400772501151409588531511454012693041857206046113283949847762202
Gy = 46316835694926478169428394003475163141307993866256225615783033603165251855960
l = 2**252 + 27742317777372353535851937790883648493 # order of G, = order of subgroup generated by G 

def add_affine(x1, y1, x2, y2):
    x1x2 = (x1 * x2) % p
    y1y2 = (y1 * y2) % p
    x1y2 = (x1 * y2) % p
    y1x2 = (y1 * x2) % p
    dx1x2y1y2 = (d * x1x2 * y1y2) % p
    numerator_x = (x1y2 + y1x2) % p
    denominator_x_inv = pow(1 + dx1x2y1y2, -1, p)
    numerator_y = (y1y2 - a * x1x2) % p
    denominator_y_inv = pow(1 - dx1x2y1y2, -1, p)
    x3 = (numerator_x * denominator_x_inv) % p
    y3 = (numerator_y * denominator_y_inv) % p
    return (x3, y3)

def double_affine(x1, y1):
    ax1x1 = (a * x1 * x1) % p
    y1y1 = (y1 * y1) % p
    numerator_x = (2 * x1 * y1) % p
    denominator_x_inv = pow(ax1x1 + y1y1, -1, p)
    numerator_y = (y1y1 - ax1x1) % p
    denominator_y_inv = pow(2 - ax1x1 - y1y1, -1, p)
    x3 = (numerator_x * denominator_x_inv) % p
    y3 = (numerator_y * denominator_y_inv) % p
    return (x3, y3)

def add_extended_homogeneous(X1, Y1, Z1, T1, X2, Y2, Z2, T2):
    A = ((Y1 - X1) * (Y2 - X2)) % p
    B = ((Y1 + X1) * (Y2 + X2)) % p
    C = (T1 * 2 * d * T2) % p
    D = (Z1 * 2 * Z2) % p
    E = (B - A) % p
    F = (D - C) % p
    G = (D + C) % p
    H = (B + A) % p
    X3 = (E * F) % p
    Y3 = (G * H) % p
    T3 = (E * H) % p
    Z3 = (F * G) % p
    return (X3, Y3, Z3, T3)

def double_extended_homogeneous(X1, Y1, Z1, T1):
    A = (X1 * X1) % p
    B = (Y1 * Y1) % p
    C = (2 * Z1 * Z1) % p
    H = (A + B) % p
    E = (H - (X1 + Y1) * (X1 + Y1)) % p
    G = (A - B) % p
    F = (C + G) % p
    X3 = (E * F) % p
    Y3 = (G * H) % p
    T3 = (E * H) % p
    Z3 = (F * G) % p
    return (X3, Y3, Z3, T3)

def affine_to_extended_homogeneous(x1, y1):
    X1 = x1
    Y1 = y1
    Z1 = 1
    T1 = (x1 * y1) % p
    return (X1, Y1, Z1, T1)

def extended_homogeneous_to_affine(X1, Y1, Z1, T1):
    Z1_inv = pow(Z1, -1, p)
    x1 = (X1 * Z1_inv) % p
    y1 = (Y1 * Z1_inv) % p
    return (x1, y1)

'''
test vectors
1*G = [15112221349535400772501151409588531511454012693041857206046113283949847762202, 46316835694926478169428394003475163141307993866256225615783033603165251855960]
2*G = [24727413235106541002554574571675588834622768167397638456726423682521233608206, 15549675580280190176352668710449542251549572066445060580507079593062643049417]
3*G = [46896733464454938657123544595386787789046198280132665686241321779790909858396, 8324843778533443976490377120369201138301417226297555316741202210403726505172]
4*G = [14582954232372986451776170844943001818709880559417862259286374126315108956272, 32483318716863467900234833297694612235682047836132991208333042722294373421359]
5*G = [33467004535436536005251147249499675200073690106659565782908757308821616914995, 43097193783671926753355113395909008640284023746042808659097434958891230611693]
l*G = [0, 1]
'''

#
# test add_affine
#
(res1Gx, res1Gy) = add_affine(Gx, Gy, 0, 1) # (0, 1): identity/neutral element
(res2Gx, res2Gy) = add_affine(Gx, Gy, Gx, Gy)
(res3Gx, res3Gy) = add_affine(res2Gx, res2Gy, Gx, Gy)
(res4Gx, res4Gy) = add_affine(res2Gx, res2Gy, res2Gx, res2Gy)
(res5Gx, res5Gy) = add_affine(res3Gx, res3Gy, res2Gx, res2Gy)
print((res1Gx, res1Gy))
print((res2Gx, res2Gy))
print((res3Gx, res3Gy))
print((res4Gx, res4Gy))
print((res5Gx, res5Gy))
print()

#
# test double_affine
#
(res2Gx, res2Gy) = double_affine(Gx, Gy)
(res4Gx, res4Gy) = double_affine(res2Gx, res2Gy)
print((res2Gx, res2Gy))
print((res4Gx, res4Gy))
print()

#
# test add_extended_homogeneous
#
(GX, GY, GZ, GT) = affine_to_extended_homogeneous(Gx, Gy)
(IX, IY, IZ, IT) = affine_to_extended_homogeneous(0, 1)
(res1GX, res1GY, res1GZ, res1GT) = add_extended_homogeneous(GX, GY, GZ, GT, IX, IY, IZ, IT)
(res2GX, res2GY, res2GZ, res2GT) = add_extended_homogeneous(GX, GY, GZ, GT, GX, GY, GZ, GT)
(res3GX, res3GY, res3GZ, res3GT) = add_extended_homogeneous(res2GX, res2GY, res2GZ, res2GT, GX, GY, GZ, GT)
(res4GX, res4GY, res4GZ, res4GT) = add_extended_homogeneous(res2GX, res2GY, res2GZ, res2GT, res2GX, res2GY, res2GZ, res2GT)
(res5GX, res5GY, res5GZ, res5GT) = add_extended_homogeneous(res3GX, res3GY, res3GZ, res3GT, res2GX, res2GY, res2GZ, res2GT)

# - normalization
(res1Gx, res1Gy) = extended_homogeneous_to_affine(res1GX, res1GY, res1GZ, res1GT)
(res2Gx, res2Gy) = extended_homogeneous_to_affine(res2GX, res2GY, res2GZ, res2GT)
(res3Gx, res3Gy) = extended_homogeneous_to_affine(res3GX, res3GY, res3GZ, res3GT)
(res4Gx, res4Gy) = extended_homogeneous_to_affine(res4GX, res4GY, res4GZ, res4GT)
(res5Gx, res5Gy) = extended_homogeneous_to_affine(res5GX, res5GY, res5GZ, res5GT)

print((res1Gx, res1Gy))
print((res2Gx, res2Gy))
print((res3Gx, res3Gy))
print((res4Gx, res4Gy))
print((res5Gx, res5Gy))
print()

#
# test double_extended_homogeneous
#
(GX, GY, GZ, GT) = affine_to_extended_homogeneous(Gx, Gy)
(res2GX, res2GY, res2GZ, res2GT) = double_extended_homogeneous(GX, GY, GZ, GT)
(res4GX, res4GY, res4GZ, res4GT) = double_extended_homogeneous(res2GX, res2GY, res2GZ, res2GT)

# - normalization
(res2Gx, res2Gy) = extended_homogeneous_to_affine(res2GX, res2GY, res2GZ, res2GT)
(res4Gx, res4Gy) = extended_homogeneous_to_affine(res4GX, res4GY, res4GZ, res4GT)

print((res2Gx, res2Gy))
print((res4Gx, res4Gy))